<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="DpiDosyaları\goodbyedpi.exe" />
    <None Remove="DpiDosyaları\WinDivert.dll" />
    <None Remove="DpiDosyaları\WinDivert64.sys" />
    <None Remove="DpiDosyaları\discord-blacklist.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="DpiDosyaları\goodbyedpi.exe" />
    <EmbeddedResource Include="DpiDosyaları\WinDivert.dll" />
    <EmbeddedResource Include="DpiDosyaları\WinDivert64.sys" />
    <EmbeddedResource Include="DpiDosyaları\discord-blacklist.txt" />
  </ItemGroup>

</Project>